# Generated by Django 4.2.11 on 2024-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
